name: dnd_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.3.2

  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  kiwi: ^4.1.0
  provider: ^6.0.5
  collection: ^1.17.1
  equatable: ^2.0.5
  rxdart: ^0.27.7
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  path_provider: ^2.1.1
  dio_smart_retry: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  kiwi_generator: ^4.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/paper.jpg
